In [42]:
import matplotlib.pyplot as plt
import numpy as np
import sklearn as sk
import math
from sklearn.cluster import KMeans
from matplotlib import pyplot as plt
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn import datasets
from random import *


# Datasets definition
# -------------------------------------------------------------------------------------------------------
digits = datasets.load_digits()
X_digits = digits.data
Y_digits = digits.target

indAll = np.arange(len(Y_digits))
np.random.shuffle(indAll)

testToTrainRatio = 0.8;
trainX=X_digits[0:int(testToTrainRatio*len(indAll))]
testX=X_digits[int(testToTrainRatio*len(indAll)):]
trainY=Y_digits[0:int(testToTrainRatio*len(indAll))]
testY=Y_digits[int(testToTrainRatio*len(indAll)):]

trainX=X_digits
trainY=Y_digits
testX=X_digits
testY=Y_digits

numberOfLayerNodes=[4,4,4]
learningCoeffitient=0.01

weights = np.zeros((len(numberOfLayerNodes), np.amax(numberOfLayerNodes),np.amax(numberOfLayerNodes)))
nodes = np.zeros((len(numberOfLayerNodes), np.amax(numberOfLayerNodes)))
weightedSums = np.zeros((len(numberOfLayerNodes), np.amax(numberOfLayerNodes)))
errors = np.zeros((len(numberOfLayerNodes), np.amax(numberOfLayerNodes)))
rowError = 0
epochError = 0
                 
def calculateHiddenLayer(layerNumber):
	ws = 0
	for x in range(0,numberOfLayerNodes[layerNumber]):
		ws = 0
		for px in range(0, numberOfLayerNodes[layerNumber - 1]):
			print("px: "+str(px))
			print("x: "+str(x))            
			print("layerNumber: "+str(layerNumber))
			ws = ws + nodes[layerNumber - 1][px] * weights[layerNumber][x][px]
			weightedSums[layerNumber][x] = ws
			nodes[layerNumber][x] = activationFunction(ws)

def populateWeightsWithRandom():
	for z in range(1, len(numberOfLayerNodes)):
		for y in range(0, len(weights[0])):
			for x in range(0, len(weights[0][0])):
				weights[z][y][x] = random() * 2 - 1

                


def activationFunction(ws):
    value = 0
    value = 1 / (1 + math.exp(-ws))
    return value                
                
    
print("-----------------------")
print(weights.shape)
print(nodes.shape)
print(weightedSums.shape)
print(errors.shape)
print(trainX.shape)
print(trainY.shape)
print(testX.shape)
print(testY.shape)

populateWeightsWithRandom()
print(weights)
calculateHiddenLayer(2)
    
    


-----------------------
(3, 4, 4)
(3, 4)
(3, 4)
(3, 4)
(1797, 64)
(1797,)
(1797, 64)
(1797,)
[[[ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[-0.70528809 -0.78913642 -0.77387438  0.15579366]
  [ 0.25927712  0.06757508 -0.76694212  0.83238542]
  [ 0.69639302 -0.27070312 -0.46189359 -0.18563623]
  [-0.10087637  0.61527802 -0.86114591 -0.59317491]]

 [[-0.68028846 -0.73753087  0.98415405  0.17757143]
  [ 0.43506148  0.70988269  0.46020989 -0.98977919]
  [-0.97255051  0.64526724 -0.9532453   0.85966289]
  [ 0.27188223 -0.47609531 -0.95541135  0.38046601]]]
px: 0
x: 0
layerNumber: 2
px: 1
x: 0
layerNumber: 2
px: 2
x: 0
layerNumber: 2
px: 3
x: 0
layerNumber: 2
px: 0
x: 1
layerNumber: 2
px: 1
x: 1
layerNumber: 2
px: 2
x: 1
layerNumber: 2
px: 3
x: 1
layerNumber: 2
px: 0
x: 2
layerNumber: 2
px: 1
x: 2
layerNumber: 2
px: 2
x: 2
layerN