In [28]:
import numpy as np

def activationFunction(x):
    return 1/(1+np.exp(-x))

def derivative(x):
    return x*(1-x)

    
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1],
            [1,1,0],
            [0,1,0]])
                
y = np.array([[0],
            [1],
            [1],
            [1],
            [0],
            [1]])

np.random.seed(1)

# randomly initialize our weights with mean 0
weights0 = 2*np.random.random((3,4)) - 1
weights1 = 2*np.random.random((4,1)) - 1
print("weights0:")
print(weights0)
print("weights1:")
print(weights1)

for j in range(60000):

    # Feed forward through layers 0, 1, and 2
    l0 = X
    l1 = activationFunction(np.dot(l0,weights0))
    l2 = activationFunction(np.dot(l1,weights1))

    # how much did we miss the target value?
    l2_error = y - l2
    
    if (j% 10000) == 0:
        print ("Error:" + str(np.mean(np.abs(l2_error))))
        
    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error*derivative(l2)

    # how much did each l1 value contribute to the l2 error (according to the weights)?
    l1_error = l2_delta.dot(weights1.T)
    
    # in what direction is the target l1?
    # were we really sure? if so, don't change too much.
    l1_delta = l1_error * derivative(l1)

    weights1 += l1.T.dot(l2_delta)
    weights0 += l0.T.dot(l1_delta)
    
print("l0:")
print(l0)
print("weights0:")
print(weights0)
print("weights1:")
print(weights1)
print("l2:")
print(l2)

syn0:
[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
syn1:
[[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]
Error:0.492666780106
Error:0.00723662356792
Error:0.00499080331527
Error:0.00403116440946
Error:0.00346884310215
Error:0.00308916026656
l0:
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]
 [1 1 0]
 [0 1 0]]
syn0:
[[ 3.60080169 -1.53444735 -6.89729834 -4.38356052]
 [-1.69969027  0.43488741 -5.51578828  2.08981052]
 [-5.59753828  2.34308882  3.29646292  6.7853767 ]]
syn1:
[[ -7.41953895]
 [  0.94815296]
 [-13.77442984]
 [  6.9479124 ]]
l2:
[[ 0.0040498 ]
 [ 0.99847508]
 [ 0.99690202]
 [ 0.99940462]
 [ 0.00375246]
 [ 0.99615457]]


In [2]:
l1

array([[ 0.72631789,  0.21589152,  0.84580526,  0.4403287 ],
       [ 0.14286982,  0.85554432,  0.10012286,  0.81904819],
       [ 0.17174678,  0.88043508,  0.09835616,  0.80257419],
       [ 0.01285639,  0.99372629,  0.00220778,  0.95899539]])

In [24]:
l0 = np.array([[0,1,0]])
l1 = nonlin(np.dot(l0,syn0))
l2 = nonlin(np.dot(l1,syn1))
l2

array([[ 0.99738533]])