In [1]:
import numpy as np

def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)

    return 1/(1+np.exp(-x))
    
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
            [1],
            [1],
            [1]])

np.random.seed(1)

# randomly initialize our weights with mean 0
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1
print("syn0:")
print(syn0)
print("syn1:")
print(syn1)

for j in range(60000):

    # Feed forward through layers 0, 1, and 2
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))

    # how much did we miss the target value?
    l2_error = y - l2
    
    if (j% 10000) == 0:
        print ("Error:" + str(np.mean(np.abs(l2_error))))
        
    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error*nonlin(l2,deriv=True)

    # how much did each l1 value contribute to the l2 error (according to the weights)?
    l1_error = l2_delta.dot(syn1.T)
    
    # in what direction is the target l1?
    # were we really sure? if so, don't change too much.
    l1_delta = l1_error * nonlin(l1,deriv=True)

    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
    
print("l0:")
print(l0)
print("syn0:")
print(syn0)
print("syn1:")
print(syn1)
print("l2:")
print(l2)

syn0:
[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
syn1:
[[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]
Error:0.474055847443
Error:0.0045588286656
Error:0.00311517548067
Error:0.00249955691379
Error:0.00214004810963
Error:0.0018980868452
l0:
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
syn0:
[[-2.54932071  3.28633051 -3.91769963  1.64229161]
 [-2.76767847  3.0685393  -3.89793538  1.74974213]
 [ 0.97602182 -1.28977276  1.70207399 -0.23982961]]
syn1:
[[-4.07255289]
 [ 5.73660514]
 [-6.59221996]
 [ 3.10324084]]
l2:
[[ 0.00265469]
 [ 0.99799026]
 [ 0.9979614 ]
 [ 0.9998177 ]]
