In [12]:
from sklearn.neural_network import MLPClassifier
from sklearn import datasets
import numpy as np
import matplotlib.pyplot as plt

digits = datasets.load_digits()
X_digits = digits.data
Y_digits = digits.target

indAll = np.arange(len(Y_digits))
np.random.shuffle(indAll)

testToTrainRatio = 0.5
trainX=X_digits[indAll[0:int(testToTrainRatio*len(indAll))]]
testX=X_digits[indAll[int(testToTrainRatio*len(indAll)):]]
trainY=Y_digits[indAll[0:int(testToTrainRatio*len(indAll))]]
testY=Y_digits[indAll[int(testToTrainRatio*len(indAll)):]]

learningCoeficient=0.01

ann = MLPClassifier(hidden_layer_sizes=(80,), # one hidden layer with 80 neurons
                    activation='logistic', # logistic sigmoid function
                    solver='adam', # stochastic gradient descent
                    alpha=1e-5, # regularization
                    random_state=1,
                    learning_rate_init = 0.002)

ann.fit(trainX, trainY)
y_predict = ann.predict(testX)
prediction_result=y_predict-testY

In [13]:
prediction_result

array([ 0, -7,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       -3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  1,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0, -5,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -7,  0,  0,
        0,  0,  0,  0,  0

In [9]:
y_predict

array([8, 1, 6, 0, 7, 8, 0, 5, 8, 4, 3, 8, 6, 1, 4, 5, 4, 3, 8, 1, 1, 1, 9,
       9, 1, 2, 0, 0, 0, 8, 1, 5, 1, 9, 5, 7, 8, 6, 0, 0, 0, 7, 3, 5, 4, 9,
       5, 9, 0, 0, 5, 3, 6, 0, 8, 1, 7, 5, 2, 5, 8, 6, 8, 1, 9, 3, 5, 3, 4,
       4, 4, 2, 9, 0, 4, 9, 5, 8, 9, 5, 6, 6, 0, 4, 2, 6, 5, 5, 6, 1, 8, 2,
       0, 0, 6, 7, 3, 8, 5, 4, 4, 6, 1, 7, 2, 2, 8, 5, 4, 3, 5, 5, 2, 4, 3,
       7, 1, 7, 1, 4, 7, 7, 0, 2, 9, 7, 2, 4, 5, 3, 7, 7, 0, 9, 5, 5, 0, 2,
       0, 1, 3, 7, 3, 1, 7, 7, 9, 3, 3, 9, 6, 8, 3, 1, 9, 8, 8, 7, 9, 0, 7,
       2, 9, 0, 5, 6, 7, 5, 6, 8, 7, 2, 1, 8, 1, 9, 8, 7, 0, 9, 0, 5, 4, 7,
       2, 7, 9, 1, 8, 9, 7, 2, 8, 4, 9, 0, 8, 4, 8, 1, 9, 2, 3, 1, 5, 2, 5,
       5, 5, 2, 2, 8, 7, 2, 6, 2, 5, 9, 9, 5, 4, 9, 7, 3, 0, 4, 8, 5, 5, 2,
       4, 1, 0, 8, 2, 9, 4, 9, 2, 7, 2, 3, 2, 1, 2, 1, 6, 5, 4, 0, 2, 8, 5,
       5, 6, 5, 6, 7, 7, 3, 0, 6, 6, 4, 4, 3, 5, 3, 8, 1, 6, 4, 0, 9, 6, 9,
       7, 0, 6, 1, 9, 6, 9, 3, 8, 5, 4, 2, 4, 4, 7, 7, 1, 5, 2, 1, 6, 2, 8,
       9, 3,

In [10]:
testY

array([8, 1, 6, 0, 7, 8, 0, 5, 8, 4, 3, 8, 6, 1, 4, 5, 4, 3, 8, 1, 1, 1, 4,
       9, 1, 2, 0, 0, 0, 8, 1, 3, 1, 9, 5, 7, 8, 6, 0, 0, 0, 7, 8, 5, 4, 9,
       5, 9, 0, 0, 5, 3, 6, 0, 8, 1, 7, 5, 2, 5, 8, 6, 8, 1, 9, 3, 5, 3, 4,
       4, 4, 2, 9, 0, 4, 9, 5, 8, 9, 8, 6, 6, 0, 4, 2, 6, 5, 5, 6, 1, 8, 2,
       0, 0, 6, 7, 3, 8, 5, 4, 4, 6, 1, 7, 2, 2, 8, 5, 4, 3, 5, 5, 2, 4, 3,
       7, 1, 7, 1, 4, 7, 7, 0, 2, 9, 7, 2, 4, 5, 3, 7, 7, 0, 9, 5, 9, 0, 2,
       0, 1, 3, 9, 3, 1, 7, 7, 9, 3, 3, 9, 6, 8, 3, 1, 9, 8, 3, 7, 9, 0, 7,
       2, 9, 0, 5, 6, 7, 5, 6, 8, 7, 2, 1, 8, 1, 9, 8, 7, 0, 9, 0, 5, 4, 7,
       2, 7, 9, 1, 8, 8, 7, 2, 8, 4, 9, 0, 8, 4, 8, 1, 9, 2, 3, 1, 5, 2, 5,
       5, 5, 2, 2, 8, 7, 2, 6, 2, 5, 9, 9, 5, 4, 9, 7, 3, 0, 4, 8, 5, 5, 2,
       4, 1, 0, 8, 2, 9, 4, 9, 2, 7, 2, 3, 2, 1, 2, 1, 6, 5, 4, 0, 2, 8, 5,
       5, 6, 5, 6, 7, 7, 3, 0, 6, 6, 4, 4, 3, 5, 3, 8, 1, 6, 4, 0, 9, 6, 9,
       7, 0, 6, 1, 9, 6, 9, 3, 8, 5, 4, 2, 4, 6, 7, 7, 1, 5, 2, 2, 6, 2, 8,
       9, 3,